#!/bin/bash
MSG="$1"
MSG=$(printf '%s\n' "$MSG" |
    tr '[:upper:]' '[:lower:]' |
    sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//')

case "$MSG" in
    *led\ on*)
        echo "Turning LED ON"
        /home/q/websd/piscripts/relayon
        ;;
    *led\ off*)
        echo "Turning LED OFF"
        /home/q/websd/piscripts/relayoff
        ;;
    *fm\ on*)
        echo "Starting FM radio"
        /home/q/websd/piscripts/fmradiophone
        ;;
    *fm\ off*)
        echo "Stopping FM radio"
        /home/q/websd/piscripts/fmphoneoff
        ;;
    *reboot*)
        echo "Rebooting Pi"
        sudo reboot
        ;;
    *)
        echo "No matching action"
        ;;
esac
