#!/bin/sh

echo "Configure serial port"
stty -F /dev/ttyUSB0 38400 cs8 -parenb -cstopb cread clocal echo icanon icrnl onlcr

echo "Send ENTER"
printf '\r' > /dev/ttyUSB0

echo "Send webs&"
printf 'webs&' > /dev/ttyUSB0

echo "Send ENTER again"
printf '\r' > /dev/ttyUSB0
