#!/bin/bash

sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o usb0 -j MASQUERADE
sudo ip route replace default via 192.168.2.2 dev usb0
sudo echo nameserver 1.1.1.1 > /etc/resolv.conf
